### ISSUE TITLE
Create a student database in MongoDB

### ISSUE THREAD

**Issue by sujal-garg** [Developer-Student-Clubs-MMDU/Database-Management-System#11]

**Comment by Siddharth-Rai-06** [comment]
I have used MongoDB in some of my projects. Please assign it to me.

**Comment by sujalgarg17** [comment]
Have assigned the issue to you have go at it @Siddharth-Rai-06

**Comment by sujalgarg17** [comment]
@Siddharth-Rai-06 you've made the PR for your code in readme please make PR in a new file

**Comment by Siddharth-Rai-06** [comment]
What type of file should I use?

**Comment by Siddharth-Rai-06** [comment]
Should I add it in a text file ?? The content is okay right ??

**Comment by sujalgarg17** [comment]
Yes

**Comment by Siddharth-Rai-06** [comment]
Hry Sujal, I have made the changes, kindly review the pull request.

**Comment by Siddharth-Rai-06** [comment]
Hey Sujal, I have resolved the conflict, plz now review and merge it.

**Comment by sujal-garg** [comment]
@Siddharth-Rai-06 has successfully completed this issue
