### ISSUE TITLE
What is mapreduce in MongoDb

### ISSUE THREAD

**Issue by sujalgarg17** [Developer-Student-Clubs-MMDU/Database-Management-System#9]

**Comment by Ritika-Pandey01** [comment]
Hey, could you please assign this to me? I would love to contribute!

**Comment by sujalgarg17** [comment]
Have assigned the issue to you, have a go at it!!

**Comment by Ritika-Pandey01** [comment]
Ok, thank you!

**Comment by sujalgarg17** [comment]
@Ritika-Pandey01 you have made PR for mapreduce in readme!!

**Comment by sujalgarg17** [comment]
This is not a readme issue so please do updations in a new file

**Comment by sujalgarg17** [comment]
Congratulations @Ritika-Pandey01 on successful submission! !
